tokens = {'acc.', 'acct.', 'add.', 'adm.', 'aet.', 'af.', 'agr.', 'ala.', 'am.', 'amp.', 'amt.',
          'anat.', 'ann.', 'app.', 'apr.', 'apt.', 'ar.', 'arch.', 'arm.', 'assn.', 'at.',
          'atm.', 'att.', 'aus.', 'aux.', 'av.', 'ax.', 'bal.', 'bar.', 'bbl.', 'bd.', 'beng.',
          'bk.', 'bl.', 'bn.', 'bor.', 'bot.', 'bp.', 'br.', 'bros.', 'bt.', 'btl.', 'bu.',
          'bul.', 'bull.', 'bur.', 'bus.', 'bx.', 'ca.', 'can.', 'cap.', 'cat.', 'cav.', 'cc.',
          'cd.', 'cdr.', 'cen.', 'cert.', 'cf.', 'cg.', 'ch.', 'chap.', 'chem.', 'chm.', 'cit.',
          'cl.', 'class.', 'cml.', 'co.', 'colloq.', 'com.', 'comm.', 'conn.', 'cons.', 'cont.',
          'coop.', 'corp.', 'corr.', 'cp.', 'cpd.', 'cr.', 'crim.', 'cs.', 'ct.', 'cts.', 'dat.',
          'dd.', 'deb.', 'dec.', 'dent.', 'der.', 'di.', 'dial.', 'dim.', 'din.', 'dir.', 'div.',
          'dk.', 'do.', 'doc.', 'dol.', 'dom.', 'dr.', 'du.', 'dz.', 'ea.', 'eccl.', 'eg.',
          'emp.', 'ens.', 'ep.', 'eq.', 'esd.', 'esp.', 'etc.', 'eth.', 'fam.', 'feb.', 'fec.',
          'fed.', 'fem.', 'ff.', 'fin.', 'fl.', 'flor.', 'fm.', 'fo.', 'for.', 'fort.', 'fr.',
          'frs.', 'ft.', 'fur.', 'fwd.', 'ga.', 'gds.', 'gen.', 'gi.', 'gl.', 'gr.', 'gro.',
          'gt.', 'hd.', 'hf.', 'hort.', 'hr.', 'ht.', 'ia.', 'ib.', 'ice.', 'ichthyol.', 'imp.',
          'inc.', 'ind.', 'indic.', 'ins.', 'inst.', 'int.', 'ir.', 'ire.', 'yrs.', 'is.',
          'ja.', 'jud.', 'kg.', 'ky.', 'kn.', 'kr.', 'kt.', 'la.', 'lab.', 'lam.', 'lang.',
          'lat.', 'lb.', 'ld.', 'lea.', 'lg.', 'lin.', 'lit.', 'lith.', 'll.', 'lt.', 'ltd.',
          'lv.', 'mach.', 'mag.', 'man.', 'mar.', 'march.', 'masc.', 'max.', 'md.', 'me.',
          'med.', 'met.', 'mi.', 'mid.', 'mil.', 'min.', 'mk.', 'ml.', 'mo.', 'mod.', 'mol.',
          'mr.', 'mrs.', 'mt.', 'mun.', 'mus.', 'ob.', 'obs.', 'oc.', 'om.', 'ont.', 'op.',
          'opp.', 'ord.', 'oz.', 'pa.', 'pal.', 'pam.', 'pan.', 'par.', 'pass.', 'pat.', 'pc.',
          'pd.', 'pen.', 'per.', 'pert.', 'pf.', 'pg.', 'phil.', 'pk.', 'pl.', 'pm.', 'pol.',
          'pos.', 'pp.', 'ppd.', 'pr.', 'prem.', 'prom.', 'pros.', 'prs.', 'ps.', 'psychol.',
          'pt.', 'pvt.', 'qr.', 'rad.', 'rd.', 're.', 'rect.', 'rit.', 'rm.', 'rom.', 'rs.',
          'rt.', 'sam.', 'sat.', 'sb.', 'sc.', 'sch.', 'sci.', 'scot.', 'scr.', 'sd.', 'sec.',
          'sem.', 'sig.', 'syr.', 'syst.', 'so.', 'sol.', 'sp.', 'spec.', 'sr.', 'sra.', 'ss.',
          'st.', 'std.', 'sw.', 'tab.', 'tbs.', 'tech.', 'temp.', 'ten.', 'ter.', 'term.',
          'terr.', 'tr.', 'tu.', 'va.', 'val.', 'var.', 'vat.', 'vb.', 'vic.', 'vo.', 'vs.',
          'vt.', 'vv.', 'wal.', 'wd.', 'wis.', 'xn.', 'xt.'}
